name = "kms-storefront"
compatibility_date = "2024-11-01"

# Pages configuration
pages_build_output_dir = ".next"

[env.production]
name = "kms-storefront-production"

[env.preview]
name = "kms-storefront-preview"
